title = "iBdB Scratchcards"
base_url = "https://nicolamarchiotto.github.io/ibdb-scratchcards-website"
description = "iBdB Scratchcards"

compile_sass = true

build_search_index = false

[markdown]
highlight_code = false

[extra]

header_links = []
